config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  mount Rapidfire::Engine => "/rapidfire"
  root to: "rapidfire/question_groups#index"
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # current user is already provided by devise
  # def current_user
  # end

  # this method will be used by rapidfire to determine whether current user
  # can manage questions or not.
  def can_administer?
    current_user.try(:email) == "admin@example.com"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title RapidfireDemo
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body
    = render partial: "shared/github_ribbon"
    = render partial: "shared/header"

    .container
      .row-fluid
        .span12
          = yield

    %br
    %br
    %br
    %br
    %br
    = render partial: "shared/footer"
    - if Rails.env.production?
      = render partial: "shared/google_analytics"

app/views/rapidfire/answer_groups/new.html.haml
%h2 Please answer these Questions
%hr

= simple_form_for([@question_group, @answer_group_builder]) do |f|
  - @answer_group_builder.answers.each do |answer|
    = f.simple_fields_for "#{answer.question.id}", answer do |answer_form|
      = render_answer_form_helper(answer, answer_form)
  = f.submit "Save", class: "btn btn-primary btn-large"

app/views/rapidfire/answers/_checkbox.html.haml
= f.input :answer_text, as: :check_boxes, collection: answer.question.options,
  label: answer.question.question_text, checked: answer.answer_text.try(:split, ",")

app/views/rapidfire/answers/_date.html.haml
= f.input :answer_text, as: :string, label: answer.question.question_text

app/views/rapidfire/answers/_long.html.haml
= f.input :answer_text, as: :text, label: answer.question.question_text,
  input_html: { rows: 5 }

app/views/rapidfire/answers/_numeric.html.haml
= f.input :answer_text, as: :string, label: answer.question.question_text

app/views/rapidfire/answers/_radio.html.haml
= f.input :answer_text, as: :radio_buttons, collection: answer.question.options,
  label: answer.question.question_text

app/views/rapidfire/answers/_select.html.haml
= f.input :answer_text, collection: answer.question.options, include_blank: true,
  label: answer.question.question_text, prompt: "Please select"

app/views/rapidfire/answers/_short.html.haml
= f.input :answer_text, as: :string, label: answer.question.question_text

app/views/rapidfire/question_groups/_form.html.haml
%h3= question_group.new_record? ? "New Survey" : "Edit Survey"

= simple_form_for question_group do |f|
  = f.input :name
  = f.submit "Save", class: "btn btn-primary btn-large"

app/views/rapidfire/question_groups/_html_results.html.haml
- results.each do |result|
  %div
    %h4
      Question:
      = result.question.question_text
    %p
      - if result.results.is_a?(Array)
        %ol
          - result.results.each do |answer|
            %li= answer
      - elsif result.results.is_a?(Hash)
        %table.table.table-striped.table-bordered
          %thead
            %tr
              %th Option
              %th Count
          %tbody
            - result.results.each do |option, count|
              %tr
                %td= option
                %td= count
  %hr

app/views/rapidfire/question_groups/_json_results.html.haml
#js-json-results

:javascript
  var charts = new ResultChart("#{question_group.id}");
  charts.render();

app/views/rapidfire/question_groups/_question_group.html.haml
%tr{ id: "question_group_#{question_group.id}" }
  %td
    - if can_administer?
      = link_to question_group.name, question_group_questions_path(question_group)
    - else
      = question_group.name

  %td
    %ul.horizontal-list
      %li
        = link_to "Take this survey", new_question_group_answer_group_path(question_group),
          class: "btn btn-primary"
      - if can_administer?
        %li
          = link_to "Results", [:results, question_group], class: "btn btn-info"
        %li
          = link_to "Delete", [question_group], method: :delete, remote: true,
            class: "btn btn-danger"

app/views/rapidfire/question_groups/destroy.js.haml
$("#question_group_#{@question_group.id}").remove();

app/views/rapidfire/question_groups/index.html.haml
%h2
  Surveys
  - if can_administer?
    .pull-right
      = link_to "New Survey", new_question_group_path, class: "btn btn-primary btn-large"
%hr

%table.table.table-striped
  %colgroup
    %col
    %col{ width: "45%" }
  %thead
    %tr
      %th Survey
      %th
  %tbody
    = render partial: "question_group", collection: @question_groups

app/views/rapidfire/question_groups/new.html.haml
= render partial: 'form', locals: {question_group: @question_group}

app/views/rapidfire/question_groups/results.html.haml
%h1 Results

%ul.nav.nav-tabs
  %li.active= link_to "JSON Results", "#json-results", "data-toggle" => "tab"
  %li= link_to "HTML Results", "#html-results", "data-toggle" => "tab"

.tab-content
  .tab-pane.active#json-results
    = render partial: "json_results", locals: { question_group: @question_group }
  .tab-pane#html-results
    = render partial: "html_results", locals: { results: @question_group_results }

app/views/rapidfire/questions/_form.html.haml
%h3 Question

= simple_form_for [@question_group, question] do |f|
  .row-fluid
    .span5
      = f.input :type, collection: Rapidfire::QuestionForm::QUESTION_TYPES,
        include_blank: false, input_html: { class: "input-xlarge" }
      = f.input :question_text, input_html: { class: "input-xlarge" }
      = f.input :answer_options, as: :text, input_html: { rows: 4, class: "input-xlarge" }

    .span6
      %h4
        %strong Other Optional Fields
      %hr

      = f.input :answer_presence, as: :boolean
      .row-fluid
        .span6
          = f.input :answer_minimum_length
        .span6
          = f.input :answer_maximum_length
      .row-fluid
        .span6
          = f.input :answer_greater_than_or_equal_to
        .span6
          = f.input :answer_less_than_or_equal_to

  %hr
  = f.submit "Save", class: "btn btn-primary btn-large"

app/views/rapidfire/questions/_question.html.haml
%tr{ id: "question_#{question.id}" }
  %td= question.question_text
  %td
    %ul.horizontal-list
      %li
        = link_to "Edit", [:edit, question.question_group, question],
          class: "btn btn-primary"
      %li
        = link_to "Delete", [question.question_group, question], method: :delete,
          class: "btn btn-danger"

app/views/rapidfire/questions/destroy.js.haml
$("#question_#{@question.id}").remove();

app/views/rapidfire/questions/edit.html.haml
= render partial: 'form', locals: {question: @question}

app/views/rapidfire/questions/index.html.haml
%h2
  Questions
  .pull-right
    = link_to "New Question", new_question_group_question_path(@question_group),
      class: "btn btn-primary btn-large"
%hr

%table.table.table-striped
  %colgroup
    %col
    %col{ width: "250" }
  %thead
    %tr
      %th Question
      %th
  %tbody
    = render partial: "question", collection: @questions

app/views/rapidfire/questions/new.html.haml
= render partial: 'form', locals: {question: @question}

app/views/shared/_footer.html.haml
%footer
  %br
  Built with love by bunch of geeks at
  = link_to "Codemancers Tech", "http://codemancers.com"

app/views/shared/_github_ribbon.html.haml
= link_to "https://github.com/code-mancers/rapidfire" do
  = image_tag "github_forkme.png", alt: "Fork me on GitHub", class: "github-ribbon"

app/views/shared/_google_analytics.html.haml
:javascript
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-42288795-1', 'herokuapp.com');
  ga('send', 'pageview');

app/views/shared/_header.html.haml
.navbar.navbar-inverse.navbar-fixed-top.index
  .navbar-inner
    .container
      = link_to "Rapidfire Demo", root_path, class: "brand"
      %button.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      .nav-collapse.collapse
        %ul.nav.pull-right
          %li
            = link_to "Surveys", rapidfire.question_groups_path
          - if current_user.nil?
            %li= link_to "Login", main_app.new_user_session_path
          - else
            %li= link_to "Logout", main_app.destroy_user_session_path, method: :delete